### PR TITLE
Add SMTP authentication and port selection, Added FriendlyName for host,ApplicationOptions save and load

### PR DESCRIPTION
**Pull request by Nirad**
Add SMTP authentication and port selection for alert email
#4  Added FriendlyName for host

Will auto upgrade your old favorite database to the new model

capture

xml

### CODE REVIEW

**Comment by R-Smith** [comment]
Looks good, @Nirad!  I'm a little busy for the next few days, but I'll merge as soon as I'm able to test it out.  Thank you.

**Comment by Nirad** [comment]
Application option are now saved and loaded from xml file
vmping

**Comment by Nirad** [comment]
I have just tested out and ipv6 work as well to. we can add this to readme.md
vmping2

**Comment by Nirad** [comment]
Implementation of detail view on double click a host #1

**Comment by Nirad** [comment]
It is ok ?

**Comment by bchynds** [comment]
+1 👍 
Built and tested.  This is just what I needed!  Thanks @Nirad!  Hopefully it gets added into master.

**Comment by R-Smith** [comment]
It's probably too late for this, but would it be possible to do separate pull requests for each of the features you added?  The smtp authentication and isolated views work great and I'd definitely like to merge those two commits.

**Comment by Nirad** [comment]
@r-smith hon do a separate

**Comment by Nirad** [comment]
You mean Application option save and Friendly name are not ok for this project ?

**Comment by stehof2** [comment]
I still miss the option to save the friendly-name in the favorite files, you need to give the connection there friendly-name every reboot.
It would also be great to save the probe options and log location in the same favorite files.

Another idea would be to let you set a deafult favorite config for every time that you start the app.
But for so far it works greats, keep up the good work!! :) :+1:

**Pull request closed without merging**
